CREATE TABLE IF NOT EXISTS stock_info (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key',
    symbol VARCHAR(32) NOT NULL COMMENT 'Stock symbol, for example 000001.SZ',
    raw_symbol VARCHAR(32) DEFAULT NULL COMMENT 'Raw symbol, for example 000001',
    name VARCHAR(128) NOT NULL COMMENT 'Stock name',
    exchange VARCHAR(32) DEFAULT NULL COMMENT 'Exchange code',
    market VARCHAR(32) DEFAULT NULL COMMENT 'Market code',
    area VARCHAR(64) DEFAULT NULL COMMENT 'Area',
    industry VARCHAR(128) DEFAULT NULL COMMENT 'Industry',
    type VARCHAR(32) DEFAULT NULL COMMENT 'Security type',
    list_date DATE DEFAULT NULL COMMENT 'List date',
    delist_date DATE DEFAULT NULL COMMENT 'Delist date',
    status VARCHAR(32) DEFAULT 'LISTED' COMMENT 'Stock status',
    is_realtime_sync_enabled TINYINT NOT NULL DEFAULT 0 COMMENT 'Whether realtime sync is enabled',
    act_ent_type VARCHAR(64) DEFAULT NULL COMMENT 'Entity type',
    data_source VARCHAR(64) DEFAULT NULL COMMENT 'Data source',
    latest_quote_date DATE DEFAULT NULL COMMENT 'Latest quote date',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    UNIQUE KEY uk_symbol (symbol),
    KEY idx_market (market),
    KEY idx_industry (industry),
    KEY idx_status (status),
    KEY idx_is_realtime_sync_enabled (is_realtime_sync_enabled),
    KEY idx_exchange (exchange)
) COMMENT='Stock info';

CREATE TABLE IF NOT EXISTS stock_income_statement (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key',
    symbol VARCHAR(32) NOT NULL COMMENT 'Stock symbol, for example 000001.SZ',
    ann_date DATE DEFAULT NULL COMMENT 'Announcement date',
    f_ann_date DATE DEFAULT NULL COMMENT 'Actual announcement date',
    end_date DATE NOT NULL COMMENT 'Report period end date',
    report_type VARCHAR(32) NOT NULL COMMENT 'Report type',
    comp_type VARCHAR(32) NOT NULL COMMENT 'Company type',
    end_type VARCHAR(32) DEFAULT NULL COMMENT 'Report period type',
    basic_eps DECIMAL(18, 6) DEFAULT NULL COMMENT 'Basic EPS',
    diluted_eps DECIMAL(18, 6) DEFAULT NULL COMMENT 'Diluted EPS',
    total_revenue DECIMAL(24, 4) DEFAULT NULL COMMENT 'Total operating revenue',
    revenue DECIMAL(24, 4) DEFAULT NULL COMMENT 'Operating revenue',
    int_income DECIMAL(24, 4) DEFAULT NULL COMMENT 'Interest income',
    comm_income DECIMAL(24, 4) DEFAULT NULL COMMENT 'Fee and commission income',
    n_commis_income DECIMAL(24, 4) DEFAULT NULL COMMENT 'Net fee and commission income',
    n_oth_income DECIMAL(24, 4) DEFAULT NULL COMMENT 'Net other operating income',
    n_oth_b_income DECIMAL(24, 4) DEFAULT NULL COMMENT 'Net other business income',
    oth_b_income DECIMAL(24, 4) DEFAULT NULL COMMENT 'Other business income',
    fv_value_chg_gain DECIMAL(24, 4) DEFAULT NULL COMMENT 'Fair value change gain',
    invest_income DECIMAL(24, 4) DEFAULT NULL COMMENT 'Investment income',
    forex_gain DECIMAL(24, 4) DEFAULT NULL COMMENT 'Foreign exchange gain',
    total_cogs DECIMAL(24, 4) DEFAULT NULL COMMENT 'Total operating costs',
    int_exp DECIMAL(24, 4) DEFAULT NULL COMMENT 'Interest expense',
    comm_exp DECIMAL(24, 4) DEFAULT NULL COMMENT 'Fee and commission expense',
    biz_tax_surchg DECIMAL(24, 4) DEFAULT NULL COMMENT 'Business tax and surcharges',
    admin_exp DECIMAL(24, 4) DEFAULT NULL COMMENT 'Administrative expense',
    oper_exp DECIMAL(24, 4) DEFAULT NULL COMMENT 'Operating expense',
    operate_profit DECIMAL(24, 4) DEFAULT NULL COMMENT 'Operating profit',
    non_oper_income DECIMAL(24, 4) DEFAULT NULL COMMENT 'Non-operating income',
    non_oper_exp DECIMAL(24, 4) DEFAULT NULL COMMENT 'Non-operating expense',
    total_profit DECIMAL(24, 4) DEFAULT NULL COMMENT 'Total profit',
    income_tax DECIMAL(24, 4) DEFAULT NULL COMMENT 'Income tax expense',
    n_income DECIMAL(24, 4) DEFAULT NULL COMMENT 'Net income',
    n_income_attr_p DECIMAL(24, 4) DEFAULT NULL COMMENT 'Net income attributable to parent shareholders',
    oth_compr_income DECIMAL(24, 4) DEFAULT NULL COMMENT 'Other comprehensive income',
    t_compr_income DECIMAL(24, 4) DEFAULT NULL COMMENT 'Total comprehensive income',
    compr_inc_attr_p DECIMAL(24, 4) DEFAULT NULL COMMENT 'Total comprehensive income attributable to parent shareholders',
    continued_net_profit DECIMAL(24, 4) DEFAULT NULL COMMENT 'Continued operating net profit',
    update_flag VARCHAR(32) DEFAULT NULL COMMENT 'Update flag',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    UNIQUE KEY uk_symbol_period_report_company (symbol, end_date, report_type, comp_type),
    KEY idx_symbol_end_date (symbol, end_date),
    KEY idx_ann_date (ann_date),
    KEY idx_f_ann_date (f_ann_date)
) COMMENT='Stock income statement by report period';

CREATE TABLE IF NOT EXISTS stock_sync_state (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key',
    symbol VARCHAR(32) NOT NULL COMMENT 'Stock symbol',
    data_type VARCHAR(64) NOT NULL COMMENT 'Sync data type',
    start_time DATETIME DEFAULT NULL COMMENT 'Current start time',
    latest_sync_time DATETIME DEFAULT NULL COMMENT 'Latest synced time',
    cursor_time DATETIME DEFAULT NULL COMMENT 'Next required processing cursor time',
    last_success_time DATETIME DEFAULT NULL COMMENT 'Last success time',
    last_failed_time DATETIME DEFAULT NULL COMMENT 'Last failed time',
    sync_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'Sync status',
    retry_count INT NOT NULL DEFAULT 0 COMMENT 'Retry count',
    data_source VARCHAR(64) DEFAULT NULL COMMENT 'Data source',
    last_error TEXT DEFAULT NULL COMMENT 'Last error',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    UNIQUE KEY uk_symbol_data_type (symbol, data_type),
    KEY idx_data_type (data_type),
    KEY idx_sync_status (sync_status),
    KEY idx_latest_sync_time (latest_sync_time),
    KEY idx_cursor_time (cursor_time)
) COMMENT='Stock sync state';

CREATE TABLE IF NOT EXISTS sync_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key',
    log_id VARCHAR(64) NOT NULL COMMENT 'Log id',
    task_id VARCHAR(64) DEFAULT NULL COMMENT 'Task id',
    symbol VARCHAR(32) NOT NULL COMMENT 'Stock symbol',
    data_type VARCHAR(64) NOT NULL COMMENT 'Data type',
    data_source VARCHAR(64) DEFAULT NULL COMMENT 'Data source',
    start_time DATETIME NOT NULL COMMENT 'Sync start time',
    end_time DATETIME NOT NULL COMMENT 'Sync end time',
    fetch_latency_ms BIGINT DEFAULT NULL COMMENT 'Fetch latency in ms',
    clean_latency_ms BIGINT DEFAULT NULL COMMENT 'Clean latency in ms',
    write_latency_ms BIGINT DEFAULT NULL COMMENT 'Write latency in ms',
    total_latency_ms BIGINT DEFAULT NULL COMMENT 'Total latency in ms',
    fetched_count INT DEFAULT 0 COMMENT 'Fetched count',
    cleaned_count INT DEFAULT 0 COMMENT 'Cleaned count',
    written_count INT DEFAULT 0 COMMENT 'Written count',
    success TINYINT NOT NULL DEFAULT 0 COMMENT 'Success flag',
    error_type VARCHAR(128) DEFAULT NULL COMMENT 'Error type',
    error_message TEXT DEFAULT NULL COMMENT 'Error message',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    UNIQUE KEY uk_log_id (log_id),
    KEY idx_task_id (task_id),
    KEY idx_symbol_data_type (symbol, data_type),
    KEY idx_success (success),
    KEY idx_created_at (created_at)
) COMMENT='Sync log';

CREATE TABLE IF NOT EXISTS trade_calendar (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key',
    exchange VARCHAR(32) NOT NULL COMMENT 'Exchange code',
    trade_date DATE NOT NULL COMMENT 'Trade date',
    is_open TINYINT NOT NULL COMMENT 'Whether the day is open for trading',
    pre_trade_date DATE DEFAULT NULL COMMENT 'Previous trade date',
    next_trade_date DATE DEFAULT NULL COMMENT 'Next trade date',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    UNIQUE KEY uk_exchange_trade_date (exchange, trade_date),
    KEY idx_trade_date (trade_date),
    KEY idx_is_open (is_open)
) COMMENT='Trade calendar';
